# Generated by Django 5.1.3 on 2024-12-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("video", "Vidéo"),
                            ("photo", "Photo"),
                            ("doc", "Document"),
                        ],
                        max_length=5,
                    ),
                ),
                ("video_url", models.URLField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
            ],
        ),
    ]
