# Generated by Django 5.1.3 on 2024-12-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="video_url",
        ),
        migrations.AddField(
            model_name="media",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
