# Generated by Django 5.1.3 on 2024-12-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_media_video_url_media_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
